ALTER TABLE users
ADD COLUMN name VARCHAR(255) NULL
AFTER email;
ALTER TABLE users
ADD COLUMN phone VARCHAR(50) NULL
AFTER name;
ALTER TABLE users
ADD COLUMN business_name VARCHAR(255) NULL
AFTER phone;