-- Database Dump generated by Casjoe SaaS
-- Date: 2025-12-24 22:03:12

SET FOREIGN_KEY_CHECKS=0;

-- Table: academy_courses
DROP TABLE IF EXISTS `academy_courses`;
CREATE TABLE `academy_courses` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `tenant_id` int(11) NOT NULL,
  `title` varchar(255) NOT NULL,
  `description` text NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `slug` varchar(255) DEFAULT NULL,
  `price` decimal(10,2) NOT NULL DEFAULT 0.00,
  `image_url` varchar(255) DEFAULT NULL,
  `category` varchar(100) DEFAULT 'Business',
  PRIMARY KEY (`id`),
  UNIQUE KEY `course_slug` (`slug`,`tenant_id`),
  KEY `tenant_id` (`tenant_id`),
  CONSTRAINT `fk_course_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenants` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Table: academy_enrollments
DROP TABLE IF EXISTS `academy_enrollments`;
CREATE TABLE `academy_enrollments` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `user_id` int(11) NOT NULL,
  `course_id` int(11) NOT NULL,
  `tenant_id` int(11) NOT NULL,
  `progress_percent` int(11) NOT NULL DEFAULT 0,
  `enrolled_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `user_course` (`user_id`,`course_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Table: academy_lessons
DROP TABLE IF EXISTS `academy_lessons`;
CREATE TABLE `academy_lessons` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `course_id` int(11) NOT NULL,
  `tenant_id` int(11) NOT NULL,
  `title` varchar(255) NOT NULL,
  `slug` varchar(255) NOT NULL,
  `video_url` varchar(255) DEFAULT NULL,
  `content` text DEFAULT NULL,
  `sort_order` int(11) NOT NULL DEFAULT 0,
  `is_free_preview` tinyint(1) NOT NULL DEFAULT 0,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `course_id` (`course_id`),
  KEY `tenant_id` (`tenant_id`),
  CONSTRAINT `fk_lessons_course` FOREIGN KEY (`course_id`) REFERENCES `academy_courses` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Table: academy_sections
DROP TABLE IF EXISTS `academy_sections`;
CREATE TABLE `academy_sections` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `course_id` int(11) NOT NULL,
  `title` varchar(255) NOT NULL,
  `sort_order` int(11) DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `course_id` (`course_id`),
  CONSTRAINT `academy_sections_ibfk_1` FOREIGN KEY (`course_id`) REFERENCES `academy_courses` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Table: billing_invoices
DROP TABLE IF EXISTS `billing_invoices`;
CREATE TABLE `billing_invoices` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `tenant_id` int(11) NOT NULL,
  `reference` varchar(100) NOT NULL,
  `amount` decimal(10,2) NOT NULL,
  `currency` varchar(3) NOT NULL DEFAULT 'USD',
  `status` enum('paid','failed','pending') NOT NULL DEFAULT 'pending',
  `date` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `tenant_id` (`tenant_id`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

INSERT INTO `billing_invoices` VALUES ('1', '1', 'INV-6949bf3fcbd64', '50000.00', 'NGN', 'paid', '2025-12-22 22:59:27'),
('2', '1', 'INV-6949c6101d61c', '50000.00', 'NGN', 'paid', '2025-12-22 23:28:32');

-- Table: cm_campaigns
DROP TABLE IF EXISTS `cm_campaigns`;
CREATE TABLE `cm_campaigns` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `tenant_id` int(11) NOT NULL,
  `name` varchar(255) NOT NULL,
  `subject` varchar(255) NOT NULL,
  `content` text NOT NULL,
  `list_id` int(11) DEFAULT NULL,
  `status` enum('draft','scheduled','sent') NOT NULL DEFAULT 'draft',
  `sent_count` int(11) NOT NULL DEFAULT 0,
  `open_count` int(11) NOT NULL DEFAULT 0,
  `sent_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `tenant_id` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Table: cm_lists
DROP TABLE IF EXISTS `cm_lists`;
CREATE TABLE `cm_lists` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `tenant_id` int(11) NOT NULL,
  `name` varchar(255) NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `tenant_id` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Table: cm_subscribers
DROP TABLE IF EXISTS `cm_subscribers`;
CREATE TABLE `cm_subscribers` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `tenant_id` int(11) NOT NULL,
  `list_id` int(11) DEFAULT NULL,
  `email` varchar(255) NOT NULL,
  `first_name` varchar(100) DEFAULT NULL,
  `last_name` varchar(100) DEFAULT NULL,
  `status` enum('subscribed','unsubscribed') NOT NULL DEFAULT 'subscribed',
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `email_list` (`email`,`list_id`,`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Table: cm_templates
DROP TABLE IF EXISTS `cm_templates`;
CREATE TABLE `cm_templates` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `tenant_id` int(11) DEFAULT NULL,
  `name` varchar(255) NOT NULL,
  `subject` varchar(255) DEFAULT NULL,
  `content` text NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

INSERT INTO `cm_templates` VALUES ('1', NULL, 'Casjoe Modern Newsletter', 'Latest Updates from {{company_name}}', '<div style=\"font-family: Arial, sans-serif; max-width: 600px; margin: auto; padding: 20px; border: 1px solid #eee;\">\r\n    <div style=\"background: #000066; color: white; padding: 20px; text-align: center;\">\r\n        <h1>Newsletter</h1>\r\n    </div>\r\n    <div style=\"padding: 20px;\">\r\n        <h2>Hello {{subscriber_name}},</h2>\r\n        <p>Here are the top stories for this week.</p>\r\n        <p>[AI Generated Content Here]</p>\r\n        <a href=\"#\" style=\"background: #FFA600; color: white; padding: 10px 20px; text-decoration: none; display: inline-block;\">Read More</a>\r\n    </div>\r\n    <div style=\"background: #f4f4f4; padding: 10px; text-align: center; font-size: 12px;\">\r\n        <p>&copy; 2024 {{company_name}}</p>\r\n        <a href=\"{{unsubscribe_url}}\">Unsubscribe</a>\r\n    </div>\r\n</div>', '2025-12-22 21:26:26'),
('2', NULL, 'Simple Announcement', 'Important Announcement', '<div style=\"font-family: sans-serif; padding: 20px;\">\r\n    <h2>Big News!</h2>\r\n    <p>Dear {{subscriber_name}},</p>\r\n    <p>We are excited to announce our new feature...</p>\r\n    <br>\r\n    <p>Best,<br>{{company_name}} Team</p>\r\n</div>', '2025-12-22 21:26:26');

-- Table: cp_payment_links
DROP TABLE IF EXISTS `cp_payment_links`;
CREATE TABLE `cp_payment_links` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `user_id` int(11) NOT NULL,
  `tenant_id` int(11) NOT NULL,
  `slug` varchar(50) NOT NULL,
  `title` varchar(255) NOT NULL,
  `amount` decimal(10,2) DEFAULT NULL COMMENT 'Null means open amount',
  `currency` varchar(3) NOT NULL DEFAULT 'NGN',
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `slug` (`slug`,`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Table: cp_transactions
DROP TABLE IF EXISTS `cp_transactions`;
CREATE TABLE `cp_transactions` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `tenant_id` int(11) NOT NULL,
  `user_id` int(11) DEFAULT NULL,
  `reference` varchar(100) NOT NULL,
  `type` enum('credit','debit') NOT NULL,
  `amount` decimal(15,2) NOT NULL,
  `currency` varchar(3) NOT NULL DEFAULT 'NGN',
  `status` enum('pending','successful','failed') NOT NULL DEFAULT 'pending',
  `description` varchar(255) DEFAULT NULL,
  `meta` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`meta`)),
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `user_id` (`user_id`),
  KEY `reference` (`reference`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

INSERT INTO `cp_transactions` VALUES ('1', '1', '1', 'FLW-69499e3375470', 'credit', '1000.00', 'NGN', 'successful', 'Wallet Funding', NULL, '2025-12-22 20:38:27');

-- Table: cp_virtual_cards
DROP TABLE IF EXISTS `cp_virtual_cards`;
CREATE TABLE `cp_virtual_cards` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `user_id` int(11) NOT NULL,
  `tenant_id` int(11) NOT NULL,
  `card_id` varchar(100) NOT NULL COMMENT 'Flutterwave Card ID',
  `start_month` varchar(2) NOT NULL,
  `start_year` varchar(2) NOT NULL,
  `masked_pan` varchar(20) NOT NULL,
  `card_type` varchar(20) DEFAULT 'MasterCard',
  `currency` varchar(3) NOT NULL DEFAULT 'USD',
  `status` enum('active','blocked','terminated') NOT NULL DEFAULT 'active',
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Table: cp_wallets
DROP TABLE IF EXISTS `cp_wallets`;
CREATE TABLE `cp_wallets` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `user_id` int(11) NOT NULL,
  `tenant_id` int(11) NOT NULL,
  `currency` varchar(3) NOT NULL DEFAULT 'NGN',
  `balance` decimal(15,2) NOT NULL DEFAULT 0.00,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `user_currency` (`user_id`,`currency`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

INSERT INTO `cp_wallets` VALUES ('1', '1', '1', 'NGN', '1000.00', '2025-12-22 18:35:12'),
('2', '3', '0', 'NGN', '0.00', '2025-12-24 19:10:04');

-- Table: cs_messages
DROP TABLE IF EXISTS `cs_messages`;
CREATE TABLE `cs_messages` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `ticket_id` int(11) NOT NULL,
  `user_id` int(11) NOT NULL,
  `message` text NOT NULL,
  `is_staff` tinyint(1) DEFAULT 0,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `ticket_id` (`ticket_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Table: cs_tickets
DROP TABLE IF EXISTS `cs_tickets`;
CREATE TABLE `cs_tickets` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `tenant_id` int(11) NOT NULL,
  `user_id` int(11) NOT NULL,
  `subject` varchar(255) NOT NULL,
  `status` enum('open','answered','closed') DEFAULT 'open',
  `priority` enum('low','medium','high') DEFAULT 'medium',
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `tenant_id` (`tenant_id`),
  KEY `user_id` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Table: erp_accounts
DROP TABLE IF EXISTS `erp_accounts`;
CREATE TABLE `erp_accounts` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `tenant_id` int(11) NOT NULL,
  `code` varchar(50) NOT NULL,
  `name` varchar(255) NOT NULL,
  `type` enum('asset','liability','equity','income','expense') NOT NULL,
  `balance` decimal(15,2) DEFAULT 0.00,
  `created_at` datetime DEFAULT current_timestamp(),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Table: erp_activity_log
DROP TABLE IF EXISTS `erp_activity_log`;
CREATE TABLE `erp_activity_log` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `tenant_id` int(11) NOT NULL,
  `user_id` int(11) DEFAULT NULL,
  `action` varchar(255) NOT NULL,
  `details` text DEFAULT NULL,
  `ip_address` varchar(45) DEFAULT NULL,
  `created_at` datetime DEFAULT current_timestamp(),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

INSERT INTO `erp_activity_log` VALUES ('1', '1', '1', 'system_init', 'System module initialized.', NULL, '2025-12-23 00:40:37');

-- Table: erp_announcements
DROP TABLE IF EXISTS `erp_announcements`;
CREATE TABLE `erp_announcements` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `tenant_id` int(11) NOT NULL,
  `title` varchar(255) NOT NULL,
  `content` text DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `created_at` datetime DEFAULT current_timestamp(),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

INSERT INTO `erp_announcements` VALUES ('1', '1', 'Welcome to Casjoe ERP', 'We are excited to launch the new modules!', NULL, '2025-12-23 00:40:37'),
('3', '1', 'Test Announcement', 'Content', '1', '2025-12-23 00:51:33');

-- Table: erp_assets
DROP TABLE IF EXISTS `erp_assets`;
CREATE TABLE `erp_assets` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `tenant_id` int(11) NOT NULL,
  `asset_name` varchar(255) NOT NULL,
  `serial_number` varchar(100) DEFAULT NULL,
  `purchase_date` date DEFAULT NULL,
  `value` decimal(10,2) DEFAULT NULL,
  `assigned_to` int(11) DEFAULT NULL,
  `status` enum('active','repair','retired','lost') DEFAULT 'active',
  `created_at` datetime DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `assigned_to` (`assigned_to`),
  CONSTRAINT `erp_assets_ibfk_1` FOREIGN KEY (`assigned_to`) REFERENCES `erp_employees` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

INSERT INTO `erp_assets` VALUES ('1', '1', 'Company Van', NULL, NULL, '25000.00', NULL, 'active', '2025-12-23 00:31:26');

-- Table: erp_attendance
DROP TABLE IF EXISTS `erp_attendance`;
CREATE TABLE `erp_attendance` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `tenant_id` int(11) NOT NULL,
  `employee_id` int(11) NOT NULL,
  `check_in` datetime NOT NULL,
  `check_out` datetime DEFAULT NULL,
  `notes` text DEFAULT NULL,
  `created_at` datetime DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `employee_id` (`employee_id`),
  CONSTRAINT `erp_attendance_ibfk_1` FOREIGN KEY (`employee_id`) REFERENCES `erp_employees` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Table: erp_chat_messages
DROP TABLE IF EXISTS `erp_chat_messages`;
CREATE TABLE `erp_chat_messages` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `tenant_id` int(11) NOT NULL,
  `user_id` int(11) NOT NULL,
  `message` text NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `tenant_id` (`tenant_id`),
  KEY `created_at` (`created_at`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

INSERT INTO `erp_chat_messages` VALUES ('1', '1', '1', 'hey', '2025-12-24 18:26:18'),
('2', '1', '1', 'hey', '2025-12-24 18:42:24'),
('3', '1', '1', 'hey', '2025-12-24 19:02:37'),
('4', '1', '3', 'how are you', '2025-12-24 19:03:32'),
('5', '1', '3', 'gey', '2025-12-24 19:09:40'),
('6', '1', '1', 'hey', '2025-12-24 19:14:34');

-- Table: erp_clients
DROP TABLE IF EXISTS `erp_clients`;
CREATE TABLE `erp_clients` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `tenant_id` int(11) NOT NULL,
  `company_name` varchar(255) NOT NULL,
  `contact_person` varchar(255) DEFAULT NULL,
  `email` varchar(255) DEFAULT NULL,
  `phone` varchar(50) DEFAULT NULL,
  `address` text DEFAULT NULL,
  `industry` varchar(100) DEFAULT NULL,
  `status` enum('active','inactive','churned') DEFAULT 'active',
  `created_at` datetime DEFAULT current_timestamp(),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

INSERT INTO `erp_clients` VALUES ('1', '1', 'Acme Corp', 'Alice Wonderland', 'alice@acme.com', NULL, NULL, NULL, 'active', '2025-12-23 00:12:49'),
('2', '1', 'Globex Inc', 'Bob Builder', 'bob@globex.com', NULL, NULL, NULL, 'active', '2025-12-23 00:12:49'),
('3', '1', 'Test Corp', 'John Test', 'client@test.com', NULL, NULL, NULL, 'active', '2025-12-23 00:14:57');

-- Table: erp_crm_customers
DROP TABLE IF EXISTS `erp_crm_customers`;
CREATE TABLE `erp_crm_customers` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `tenant_id` int(11) NOT NULL,
  `name` varchar(255) NOT NULL,
  `email` varchar(255) DEFAULT NULL,
  `phone` varchar(50) DEFAULT NULL,
  `company` varchar(255) DEFAULT NULL,
  `address` text DEFAULT NULL,
  `status` enum('active','inactive') DEFAULT 'active',
  `created_at` datetime DEFAULT current_timestamp(),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1002 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

INSERT INTO `erp_crm_customers` VALUES ('1', '1', 'Acme Corp 3486', NULL, NULL, 'Acme Inc', NULL, 'active', '2025-12-23 01:43:12'),
('999', '1', 'Sales Test Customer', NULL, NULL, NULL, NULL, 'active', '2025-12-23 01:57:17'),
('1000', '1', 'Test Client', 'testclient_1766600123@example.com', NULL, 'Test Corp', NULL, 'active', '2025-12-24 19:15:23'),
('1001', '1', 'democlient', 'democlient@example.com', '07035323038', 'Demo Client', NULL, 'active', '2025-12-24 19:21:58');

-- Table: erp_crm_leads
DROP TABLE IF EXISTS `erp_crm_leads`;
CREATE TABLE `erp_crm_leads` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `tenant_id` int(11) NOT NULL,
  `name` varchar(255) NOT NULL,
  `email` varchar(255) DEFAULT NULL,
  `phone` varchar(50) DEFAULT NULL,
  `source` varchar(100) DEFAULT NULL,
  `status` enum('new','contacted','qualified','lost') DEFAULT 'new',
  `assigned_to` int(11) DEFAULT NULL,
  `created_at` datetime DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `assigned_to` (`assigned_to`),
  CONSTRAINT `erp_crm_leads_ibfk_1` FOREIGN KEY (`assigned_to`) REFERENCES `erp_employees` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

INSERT INTO `erp_crm_leads` VALUES ('1', '1', 'John Doe Lead 4480', NULL, NULL, 'Website', 'new', NULL, '2025-12-23 01:43:12');

-- Table: erp_crm_opportunities
DROP TABLE IF EXISTS `erp_crm_opportunities`;
CREATE TABLE `erp_crm_opportunities` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `tenant_id` int(11) NOT NULL,
  `title` varchar(255) NOT NULL,
  `value` decimal(10,2) DEFAULT 0.00,
  `stage` enum('prospecting','negotiation','closed-won','closed-lost') DEFAULT 'prospecting',
  `lead_id` int(11) DEFAULT NULL,
  `customer_id` int(11) DEFAULT NULL,
  `close_date` date DEFAULT NULL,
  `created_at` datetime DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `lead_id` (`lead_id`),
  KEY `customer_id` (`customer_id`),
  CONSTRAINT `erp_crm_opportunities_ibfk_1` FOREIGN KEY (`lead_id`) REFERENCES `erp_crm_leads` (`id`) ON DELETE SET NULL,
  CONSTRAINT `erp_crm_opportunities_ibfk_2` FOREIGN KEY (`customer_id`) REFERENCES `erp_crm_customers` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

INSERT INTO `erp_crm_opportunities` VALUES ('1', '1', 'Big Deal', '5000.00', 'prospecting', NULL, '999', NULL, '2025-12-23 01:57:17'),
('2', '1', 'Big Deal', '5000.00', 'prospecting', NULL, '999', NULL, '2025-12-23 02:13:01');

-- Table: erp_crm_sale_items
DROP TABLE IF EXISTS `erp_crm_sale_items`;
CREATE TABLE `erp_crm_sale_items` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `sale_id` int(11) NOT NULL,
  `inventory_item_id` int(11) NOT NULL,
  `quantity` int(11) NOT NULL,
  `unit_price` decimal(10,2) NOT NULL,
  `total_price` decimal(10,2) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `sale_id` (`sale_id`),
  KEY `inventory_item_id` (`inventory_item_id`),
  CONSTRAINT `erp_crm_sale_items_ibfk_1` FOREIGN KEY (`sale_id`) REFERENCES `erp_crm_sales` (`id`) ON DELETE CASCADE,
  CONSTRAINT `erp_crm_sale_items_ibfk_2` FOREIGN KEY (`inventory_item_id`) REFERENCES `erp_inventory_items` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

INSERT INTO `erp_crm_sale_items` VALUES ('1', '1', '2', '5', '50.00', '250.00'),
('2', '2', '2', '5', '50.00', '250.00');

-- Table: erp_crm_sales
DROP TABLE IF EXISTS `erp_crm_sales`;
CREATE TABLE `erp_crm_sales` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `tenant_id` int(11) NOT NULL,
  `customer_id` int(11) NOT NULL,
  `total_amount` decimal(10,2) NOT NULL DEFAULT 0.00,
  `status` enum('pending','completed','cancelled') DEFAULT 'pending',
  `sale_date` datetime DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `customer_id` (`customer_id`),
  CONSTRAINT `erp_crm_sales_ibfk_1` FOREIGN KEY (`customer_id`) REFERENCES `erp_crm_customers` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

INSERT INTO `erp_crm_sales` VALUES ('1', '1', '999', '250.00', 'completed', '2025-12-23 01:57:17'),
('2', '1', '999', '250.00', 'completed', '2025-12-23 02:13:01');

-- Table: erp_crm_stages
DROP TABLE IF EXISTS `erp_crm_stages`;
CREATE TABLE `erp_crm_stages` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `tenant_id` int(11) NOT NULL,
  `name` varchar(50) NOT NULL,
  `color` varchar(20) DEFAULT '#cccccc',
  `sort_order` int(11) DEFAULT 0,
  `created_at` datetime DEFAULT current_timestamp(),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

INSERT INTO `erp_crm_stages` VALUES ('1', '1', 'New Lead', '#3498db', '1', '2025-12-23 18:04:39'),
('2', '1', 'Contacted', '#f1c40f', '2', '2025-12-23 18:04:39'),
('3', '1', 'Proposal Sent', '#e67e22', '3', '2025-12-23 18:04:39'),
('4', '1', 'Negotiation', '#9b59b6', '4', '2025-12-23 18:04:39'),
('5', '1', 'Won', '#27ae60', '5', '2025-12-23 18:04:39'),
('6', '1', 'Lost', '#c0392b', '6', '2025-12-23 18:04:39');

-- Table: erp_customers
DROP TABLE IF EXISTS `erp_customers`;
CREATE TABLE `erp_customers` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `tenant_id` int(11) NOT NULL,
  `name` varchar(255) NOT NULL,
  `email` varchar(255) DEFAULT NULL,
  `phone` varchar(50) DEFAULT NULL,
  `company` varchar(255) DEFAULT NULL,
  `status` enum('lead','customer','inactive') NOT NULL DEFAULT 'lead',
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `tenant_id` (`tenant_id`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

INSERT INTO `erp_customers` VALUES ('1', '1', 'Tech Solutions Ltd', 'contact@techsol.com', '080-1234-5678', 'Tech Solutions', 'customer', '2025-12-22 21:10:41'),
('2', '1', 'Jane Doe', 'jane.doe@gmail.com', '090-9876-5432', 'Freelancer', 'lead', '2025-12-22 21:10:41');

-- Table: erp_departments
DROP TABLE IF EXISTS `erp_departments`;
CREATE TABLE `erp_departments` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `tenant_id` int(11) NOT NULL,
  `name` varchar(255) NOT NULL,
  `description` text DEFAULT NULL,
  `created_at` datetime DEFAULT current_timestamp(),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

INSERT INTO `erp_departments` VALUES ('1', '1', 'Human Resources', 'Handles employee relations and payroll', '2025-12-22 23:49:47'),
('2', '1', 'IT & Engineering', 'Software development and infrastructure', '2025-12-22 23:49:47'),
('3', '1', 'Sales & Marketing', 'Driving revenue and brand awareness', '2025-12-22 23:49:47'),
('5', '1', 'Test Dept', 'A test department', '2025-12-23 00:08:52');

-- Table: erp_employee_lifecycle
DROP TABLE IF EXISTS `erp_employee_lifecycle`;
CREATE TABLE `erp_employee_lifecycle` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `tenant_id` int(11) NOT NULL,
  `employee_id` int(11) NOT NULL,
  `type` enum('promotion','resignation','termination') NOT NULL,
  `date` date NOT NULL,
  `reason` text DEFAULT NULL,
  `new_position` varchar(255) DEFAULT NULL,
  `created_at` datetime DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `employee_id` (`employee_id`),
  CONSTRAINT `erp_employee_lifecycle_ibfk_1` FOREIGN KEY (`employee_id`) REFERENCES `erp_employees` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Table: erp_employees
DROP TABLE IF EXISTS `erp_employees`;
CREATE TABLE `erp_employees` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `tenant_id` int(11) NOT NULL,
  `user_id` int(11) DEFAULT NULL,
  `department_id` int(11) DEFAULT NULL,
  `first_name` varchar(100) NOT NULL,
  `last_name` varchar(100) NOT NULL,
  `email` varchar(255) NOT NULL,
  `phone` varchar(50) DEFAULT NULL,
  `job_title` varchar(100) DEFAULT NULL,
  `hire_date` date DEFAULT NULL,
  `salary` decimal(10,2) DEFAULT 0.00,
  `status` enum('active','on_leave','terminated','resigned') DEFAULT 'active',
  `created_at` datetime DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `department_id` (`department_id`),
  CONSTRAINT `erp_employees_ibfk_1` FOREIGN KEY (`department_id`) REFERENCES `erp_departments` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

INSERT INTO `erp_employees` VALUES ('5', '1', NULL, '5', 'Casper', 'Okpara', 'casperjoeokpara@gmail.com', NULL, 'CEO', '2025-12-24', '600000.00', 'active', '2025-12-24 18:43:43');

-- Table: erp_estimate_items
DROP TABLE IF EXISTS `erp_estimate_items`;
CREATE TABLE `erp_estimate_items` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `estimate_id` int(11) NOT NULL,
  `description` varchar(255) NOT NULL,
  `quantity` decimal(10,2) NOT NULL DEFAULT 1.00,
  `unit_price` decimal(15,2) NOT NULL DEFAULT 0.00,
  `amount` decimal(15,2) NOT NULL DEFAULT 0.00,
  PRIMARY KEY (`id`),
  KEY `estimate_id` (`estimate_id`),
  CONSTRAINT `erp_estimate_items_ibfk_1` FOREIGN KEY (`estimate_id`) REFERENCES `erp_estimates` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Table: erp_estimates
DROP TABLE IF EXISTS `erp_estimates`;
CREATE TABLE `erp_estimates` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `tenant_id` int(11) NOT NULL,
  `uuid` varchar(64) NOT NULL,
  `client_name` varchar(255) NOT NULL,
  `client_email` varchar(255) DEFAULT NULL,
  `issue_date` date NOT NULL,
  `expiry_date` date NOT NULL,
  `total_amount` decimal(15,2) NOT NULL DEFAULT 0.00,
  `status` enum('draft','sent','accepted','rejected','converted') DEFAULT 'draft',
  `notes` text DEFAULT NULL,
  `created_at` datetime DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uuid` (`uuid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Table: erp_expenses
DROP TABLE IF EXISTS `erp_expenses`;
CREATE TABLE `erp_expenses` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `tenant_id` int(11) NOT NULL,
  `vendor_id` int(11) DEFAULT NULL,
  `description` varchar(255) NOT NULL,
  `amount` decimal(15,2) NOT NULL,
  `date` date NOT NULL,
  `category` varchar(100) DEFAULT NULL,
  `receipt_path` varchar(255) DEFAULT NULL,
  `status` enum('pending','approved','rejected') DEFAULT 'approved',
  `created_at` datetime DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `vendor_id` (`vendor_id`),
  CONSTRAINT `erp_expenses_ibfk_1` FOREIGN KEY (`vendor_id`) REFERENCES `erp_vendors` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Table: erp_gl_accounts
DROP TABLE IF EXISTS `erp_gl_accounts`;
CREATE TABLE `erp_gl_accounts` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `tenant_id` int(11) NOT NULL,
  `code` varchar(20) NOT NULL,
  `name` varchar(255) NOT NULL,
  `type` enum('asset','liability','equity','income','expense') NOT NULL,
  `balance` decimal(15,2) NOT NULL DEFAULT 0.00,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `code` (`code`,`tenant_id`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

INSERT INTO `erp_gl_accounts` VALUES ('1', '1', '1000', 'Cash', 'asset', '50000.00', '2025-12-22 21:10:41'),
('2', '1', '4000', 'Sales Revenue', 'income', '120000.00', '2025-12-22 21:10:41'),
('3', '1', '6000', 'Salaries Expense', 'expense', '45000.00', '2025-12-22 21:10:41');

-- Table: erp_inventory
DROP TABLE IF EXISTS `erp_inventory`;
CREATE TABLE `erp_inventory` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `tenant_id` int(11) NOT NULL,
  `item_name` varchar(255) NOT NULL,
  `sku` varchar(100) DEFAULT NULL,
  `quantity` int(11) DEFAULT 0,
  `unit_price` decimal(10,2) DEFAULT 0.00,
  `category` varchar(100) DEFAULT NULL,
  `created_at` datetime DEFAULT current_timestamp(),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

INSERT INTO `erp_inventory` VALUES ('1', '1', 'Office Laptop', 'DL-5500', '5', '1200.00', NULL, '2025-12-23 00:31:26'),
('2', '1', 'Ergonomic Chair', 'HM-AERON', '10', '800.00', NULL, '2025-12-23 00:31:26'),
('3', '1', 'Test Laptop', 'TEST-001', '50', '999.99', NULL, '2025-12-23 00:47:04');

-- Table: erp_inventory_items
DROP TABLE IF EXISTS `erp_inventory_items`;
CREATE TABLE `erp_inventory_items` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `tenant_id` int(11) NOT NULL,
  `sku` varchar(50) NOT NULL,
  `name` varchar(255) NOT NULL,
  `description` text DEFAULT NULL,
  `unit_price` decimal(10,2) NOT NULL DEFAULT 0.00,
  `stock_quantity` int(11) NOT NULL DEFAULT 0,
  `status` enum('active','inactive') DEFAULT 'active',
  `created_at` datetime DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_sku` (`tenant_id`,`sku`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

INSERT INTO `erp_inventory_items` VALUES ('1', '1', 'TEST-SKU-6877', 'Test Product', NULL, '99.99', '100', 'active', '2025-12-23 01:53:04'),
('2', '1', 'SALE-TEST', 'Sale Item', NULL, '50.00', '95', 'active', '2025-12-23 01:57:17'),
('4', '1', 'TEST-SKU-2452', 'Test Product', NULL, '99.99', '100', 'active', '2025-12-23 08:45:26'),
('5', '1', 'TEST-SKU-5500', 'Test Product', NULL, '99.99', '100', 'active', '2025-12-23 11:18:32');

-- Table: erp_invoice_items
DROP TABLE IF EXISTS `erp_invoice_items`;
CREATE TABLE `erp_invoice_items` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `invoice_id` int(11) NOT NULL,
  `description` varchar(255) NOT NULL,
  `quantity` decimal(10,2) NOT NULL DEFAULT 1.00,
  `unit_price` decimal(15,2) NOT NULL DEFAULT 0.00,
  `amount` decimal(15,2) NOT NULL DEFAULT 0.00,
  PRIMARY KEY (`id`),
  KEY `invoice_id` (`invoice_id`),
  CONSTRAINT `erp_invoice_items_ibfk_1` FOREIGN KEY (`invoice_id`) REFERENCES `erp_invoices` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

INSERT INTO `erp_invoice_items` VALUES ('1', '1', 'Microphone', '2.00', '100.00', '200.00'),
('2', '1', 'Sex', '1.00', '200.00', '200.00');

-- Table: erp_invoices
DROP TABLE IF EXISTS `erp_invoices`;
CREATE TABLE `erp_invoices` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `tenant_id` int(11) NOT NULL,
  `uuid` varchar(64) NOT NULL,
  `client_name` varchar(255) NOT NULL,
  `client_email` varchar(255) DEFAULT NULL,
  `issue_date` date NOT NULL,
  `due_date` date NOT NULL,
  `total_amount` decimal(15,2) NOT NULL DEFAULT 0.00,
  `status` enum('draft','sent','paid','overdue','cancelled') DEFAULT 'draft',
  `notes` text DEFAULT NULL,
  `created_at` datetime DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uuid` (`uuid`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

INSERT INTO `erp_invoices` VALUES ('1', '1', '7c9c2f1ec5511d778da2052aaf941178', 'Miracle Casper Joe', 'miraclecasperjoe@gmail.com', '2025-12-23', '2025-12-24', '400.00', 'paid', 'Kindly pay to my account using this invoice', '2025-12-23 17:54:39');

-- Table: erp_job_applications
DROP TABLE IF EXISTS `erp_job_applications`;
CREATE TABLE `erp_job_applications` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `tenant_id` int(11) NOT NULL,
  `job_id` int(11) NOT NULL,
  `candidate_name` varchar(255) NOT NULL,
  `email` varchar(255) NOT NULL,
  `resume_path` varchar(255) DEFAULT NULL,
  `status` enum('received','shortlisted','rejected','hired') DEFAULT 'received',
  `created_at` datetime DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `job_id` (`job_id`),
  CONSTRAINT `erp_job_applications_ibfk_1` FOREIGN KEY (`job_id`) REFERENCES `erp_job_postings` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

INSERT INTO `erp_job_applications` VALUES ('1', '1', '1', 'Jane Tester', 'jane@test.com', NULL, 'received', '2025-12-23 01:33:43');

-- Table: erp_job_postings
DROP TABLE IF EXISTS `erp_job_postings`;
CREATE TABLE `erp_job_postings` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `tenant_id` int(11) NOT NULL,
  `title` varchar(255) NOT NULL,
  `department` varchar(100) DEFAULT NULL,
  `description` text DEFAULT NULL,
  `status` enum('open','closed') DEFAULT 'open',
  `created_at` datetime DEFAULT current_timestamp(),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

INSERT INTO `erp_job_postings` VALUES ('1', '1', 'Verification Dev', 'IT', 'Test Job', 'open', '2025-12-23 01:33:43'),
('2', '1', 'Sales and Marketing', 'Marketing Department', 'We need sales and marketing who can make sales for Casjoe', 'open', '2025-12-23 06:54:36');

-- Table: erp_journal_entries
DROP TABLE IF EXISTS `erp_journal_entries`;
CREATE TABLE `erp_journal_entries` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `tenant_id` int(11) NOT NULL,
  `reference` varchar(50) DEFAULT NULL,
  `description` text DEFAULT NULL,
  `date` date NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `tenant_id` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Table: erp_journal_items
DROP TABLE IF EXISTS `erp_journal_items`;
CREATE TABLE `erp_journal_items` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `entry_id` int(11) NOT NULL,
  `account_id` int(11) NOT NULL,
  `debit` decimal(15,2) NOT NULL DEFAULT 0.00,
  `credit` decimal(15,2) NOT NULL DEFAULT 0.00,
  PRIMARY KEY (`id`),
  KEY `entry_id` (`entry_id`),
  KEY `fk_ji_account` (`account_id`),
  CONSTRAINT `fk_ji_account` FOREIGN KEY (`account_id`) REFERENCES `erp_gl_accounts` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_ji_entry` FOREIGN KEY (`entry_id`) REFERENCES `erp_journal_entries` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Table: erp_leads
DROP TABLE IF EXISTS `erp_leads`;
CREATE TABLE `erp_leads` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `tenant_id` int(11) NOT NULL,
  `first_name` varchar(100) DEFAULT NULL,
  `last_name` varchar(100) DEFAULT NULL,
  `company` varchar(255) DEFAULT NULL,
  `email` varchar(255) DEFAULT NULL,
  `phone` varchar(50) DEFAULT NULL,
  `source` varchar(100) DEFAULT 'Website',
  `status` enum('new','contacted','qualified','proposal','negotiation','won','lost') DEFAULT 'new',
  `created_at` datetime DEFAULT current_timestamp(),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

INSERT INTO `erp_leads` VALUES ('1', '1', 'Charlie', 'Chocolate', 'Wonka Industries', 'charlie@wonka.com', NULL, 'Website', 'new', '2025-12-23 00:12:49'),
('2', '1', 'Test', 'Lead', NULL, 'testlead@example.com', NULL, 'website', 'new', '2025-12-23 00:51:33');

-- Table: erp_leave_requests
DROP TABLE IF EXISTS `erp_leave_requests`;
CREATE TABLE `erp_leave_requests` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `tenant_id` int(11) NOT NULL,
  `employee_id` int(11) NOT NULL,
  `leave_type` enum('annual','sick','unpaid','maternity','paternity','other') NOT NULL,
  `start_date` date NOT NULL,
  `end_date` date NOT NULL,
  `status` enum('pending','approved','rejected') DEFAULT 'pending',
  `reason` text DEFAULT NULL,
  `created_at` datetime DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `employee_id` (`employee_id`),
  CONSTRAINT `erp_leave_requests_ibfk_1` FOREIGN KEY (`employee_id`) REFERENCES `erp_employees` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Table: erp_payroll
DROP TABLE IF EXISTS `erp_payroll`;
CREATE TABLE `erp_payroll` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `tenant_id` int(11) NOT NULL,
  `employee_id` int(11) NOT NULL,
  `pay_period_start` date NOT NULL,
  `pay_period_end` date NOT NULL,
  `payment_date` date NOT NULL,
  `gross_pay` decimal(10,2) NOT NULL,
  `net_pay` decimal(10,2) NOT NULL,
  `status` enum('draft','paid','cancelled') DEFAULT 'draft',
  `created_at` datetime DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `employee_id` (`employee_id`),
  CONSTRAINT `erp_payroll_ibfk_1` FOREIGN KEY (`employee_id`) REFERENCES `erp_employees` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Table: erp_payroll_items
DROP TABLE IF EXISTS `erp_payroll_items`;
CREATE TABLE `erp_payroll_items` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `payroll_id` int(11) NOT NULL,
  `type` enum('earning','deduction') NOT NULL,
  `description` varchar(255) NOT NULL,
  `amount` decimal(10,2) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `payroll_id` (`payroll_id`),
  CONSTRAINT `erp_payroll_items_ibfk_1` FOREIGN KEY (`payroll_id`) REFERENCES `erp_payroll` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Table: erp_performance_reviews
DROP TABLE IF EXISTS `erp_performance_reviews`;
CREATE TABLE `erp_performance_reviews` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `tenant_id` int(11) NOT NULL,
  `employee_id` int(11) NOT NULL,
  `reviewer_id` int(11) DEFAULT NULL,
  `review_date` date NOT NULL,
  `rating` int(11) NOT NULL CHECK (`rating` >= 1 and `rating` <= 5),
  `comments` text DEFAULT NULL,
  `created_at` datetime DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `employee_id` (`employee_id`),
  CONSTRAINT `erp_performance_reviews_ibfk_1` FOREIGN KEY (`employee_id`) REFERENCES `erp_employees` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Table: erp_products
DROP TABLE IF EXISTS `erp_products`;
CREATE TABLE `erp_products` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `tenant_id` int(11) NOT NULL,
  `name` varchar(255) NOT NULL,
  `sku` varchar(100) NOT NULL,
  `price` decimal(10,2) NOT NULL DEFAULT 0.00,
  `cost` decimal(10,2) NOT NULL DEFAULT 0.00,
  `stock_level` int(11) NOT NULL DEFAULT 0,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `sku` (`sku`,`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Table: erp_project_time_logs
DROP TABLE IF EXISTS `erp_project_time_logs`;
CREATE TABLE `erp_project_time_logs` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `tenant_id` int(11) NOT NULL,
  `project_id` int(11) DEFAULT NULL,
  `task_id` int(11) DEFAULT NULL,
  `employee_id` int(11) DEFAULT NULL,
  `description` varchar(255) DEFAULT NULL,
  `start_time` datetime DEFAULT NULL,
  `end_time` datetime DEFAULT NULL,
  `duration_minutes` int(11) DEFAULT 0,
  `created_at` datetime DEFAULT current_timestamp(),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

INSERT INTO `erp_project_time_logs` VALUES ('1', '1', '1', NULL, '5', 'A man inside the river', '2025-12-24 20:01:00', '2025-12-25 22:03:00', '1562', '2025-12-24 19:00:07');

-- Table: erp_projects
DROP TABLE IF EXISTS `erp_projects`;
CREATE TABLE `erp_projects` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `tenant_id` int(11) NOT NULL,
  `name` varchar(255) NOT NULL,
  `description` text DEFAULT NULL,
  `client_id` int(11) DEFAULT NULL,
  `start_date` date DEFAULT NULL,
  `end_date` date DEFAULT NULL,
  `status` enum('not_started','in_progress','on_hold','completed','cancelled') DEFAULT 'not_started',
  `created_at` datetime DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `client_id` (`client_id`),
  CONSTRAINT `erp_projects_ibfk_1` FOREIGN KEY (`client_id`) REFERENCES `erp_clients` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

INSERT INTO `erp_projects` VALUES ('1', '1', 'Website Redesign', 'Revamp corporate website', NULL, NULL, NULL, 'in_progress', '2025-12-23 00:18:34'),
('2', '1', 'Mobile App Launch', 'Launch Android version', NULL, NULL, NULL, 'not_started', '2025-12-23 00:18:34'),
('3', '1', 'Verify Project', 'A test project', NULL, NULL, NULL, 'not_started', '2025-12-23 00:23:03');

-- Table: erp_push_subscriptions
DROP TABLE IF EXISTS `erp_push_subscriptions`;
CREATE TABLE `erp_push_subscriptions` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `user_id` int(11) NOT NULL,
  `endpoint` text NOT NULL,
  `keys_p256dh` text NOT NULL,
  `keys_auth` text NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `user_id` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Table: erp_settings
DROP TABLE IF EXISTS `erp_settings`;
CREATE TABLE `erp_settings` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `tenant_id` int(11) NOT NULL,
  `setting_key` varchar(100) NOT NULL,
  `setting_value` text DEFAULT NULL,
  `created_at` datetime DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_setting` (`tenant_id`,`setting_key`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

INSERT INTO `erp_settings` VALUES ('1', '1', 'company_name', 'Casjoe LLC', '2025-12-23 00:40:37'),
('2', '1', 'timezone', 'UTC', '2025-12-23 00:40:37');

-- Table: erp_tasks
DROP TABLE IF EXISTS `erp_tasks`;
CREATE TABLE `erp_tasks` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `tenant_id` int(11) NOT NULL,
  `project_id` int(11) NOT NULL,
  `title` varchar(255) NOT NULL,
  `description` text DEFAULT NULL,
  `assigned_to` int(11) DEFAULT NULL,
  `due_date` date DEFAULT NULL,
  `priority` enum('low','medium','high') DEFAULT 'medium',
  `status` enum('todo','in_progress','review','done') DEFAULT 'todo',
  `created_at` datetime DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `project_id` (`project_id`),
  KEY `assigned_to` (`assigned_to`),
  CONSTRAINT `erp_tasks_ibfk_1` FOREIGN KEY (`project_id`) REFERENCES `erp_projects` (`id`) ON DELETE CASCADE,
  CONSTRAINT `erp_tasks_ibfk_2` FOREIGN KEY (`assigned_to`) REFERENCES `erp_employees` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

INSERT INTO `erp_tasks` VALUES ('1', '1', '1', 'Design Mockups', NULL, NULL, NULL, 'medium', 'done', '2025-12-23 00:18:34'),
('2', '1', '1', 'Develop API', NULL, NULL, NULL, 'medium', 'in_progress', '2025-12-23 00:18:34'),
('4', '1', '1', 'Test Task', 'Desc', NULL, '2025-12-23', 'high', 'todo', '2025-12-23 00:51:33');

-- Table: erp_training_enrollments
DROP TABLE IF EXISTS `erp_training_enrollments`;
CREATE TABLE `erp_training_enrollments` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `tenant_id` int(11) NOT NULL,
  `program_id` int(11) NOT NULL,
  `employee_id` int(11) NOT NULL,
  `status` enum('enrolled','completed','dropped') DEFAULT 'enrolled',
  PRIMARY KEY (`id`),
  KEY `program_id` (`program_id`),
  KEY `employee_id` (`employee_id`),
  CONSTRAINT `erp_training_enrollments_ibfk_1` FOREIGN KEY (`program_id`) REFERENCES `erp_training_programs` (`id`) ON DELETE CASCADE,
  CONSTRAINT `erp_training_enrollments_ibfk_2` FOREIGN KEY (`employee_id`) REFERENCES `erp_employees` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Table: erp_training_programs
DROP TABLE IF EXISTS `erp_training_programs`;
CREATE TABLE `erp_training_programs` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `tenant_id` int(11) NOT NULL,
  `name` varchar(255) NOT NULL,
  `instructor` varchar(255) DEFAULT NULL,
  `start_date` date DEFAULT NULL,
  `end_date` date DEFAULT NULL,
  `status` enum('scheduled','in_progress','completed','cancelled') DEFAULT 'scheduled',
  `created_at` datetime DEFAULT current_timestamp(),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

INSERT INTO `erp_training_programs` VALUES ('1', '1', 'Verification Training', 'Dr. Check', '2025-05-01', '2025-05-05', 'scheduled', '2025-12-23 01:37:17');

-- Table: erp_transactions
DROP TABLE IF EXISTS `erp_transactions`;
CREATE TABLE `erp_transactions` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `tenant_id` int(11) NOT NULL,
  `description` varchar(255) NOT NULL,
  `amount` decimal(10,2) NOT NULL,
  `type` enum('income','expense') NOT NULL,
  `date` date NOT NULL,
  `category` varchar(100) DEFAULT NULL,
  `created_at` datetime DEFAULT current_timestamp(),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

INSERT INTO `erp_transactions` VALUES ('1', '1', 'Client Payment', '5000.00', 'income', '2025-12-23', NULL, '2025-12-23 00:31:26'),
('2', '1', 'Office Rent', '2000.00', 'expense', '2025-12-23', NULL, '2025-12-23 00:31:26'),
('3', '1', 'Invoice Payment #1', '400.00', 'income', '2025-12-23', NULL, '2025-12-23 17:54:52');

-- Table: erp_vendors
DROP TABLE IF EXISTS `erp_vendors`;
CREATE TABLE `erp_vendors` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `tenant_id` int(11) NOT NULL,
  `name` varchar(255) NOT NULL,
  `email` varchar(255) DEFAULT NULL,
  `phone` varchar(50) DEFAULT NULL,
  `address` text DEFAULT NULL,
  `created_at` datetime DEFAULT current_timestamp(),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Table: modules
DROP TABLE IF EXISTS `modules`;
CREATE TABLE `modules` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(100) NOT NULL,
  `slug` varchar(50) NOT NULL,
  `description` text DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `slug` (`slug`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

INSERT INTO `modules` VALUES ('1', 'Casjoe ERP', 'casjoe-erp', 'Core ERP Module', '2025-12-22 18:17:04'),
('2', 'Casjoe Pay', 'casjoe-pay', 'Payment Suite', '2025-12-22 18:34:05'),
('3', 'Casjoe Academy', 'casjoe-academy', 'LMS & Courses', '2025-12-22 18:34:05'),
('4', 'Casjoe Mail', 'casjoe-mail', 'Email Marketing', '2025-12-22 18:34:05'),
('5', 'Casjoe Support', 'casjoe-support', 'Helpdesk & Ticketing', '2025-12-22 18:55:18');

-- Table: notifications
DROP TABLE IF EXISTS `notifications`;
CREATE TABLE `notifications` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `tenant_id` int(11) NOT NULL,
  `user_id` int(11) NOT NULL,
  `title` varchar(255) NOT NULL,
  `message` text DEFAULT NULL,
  `link` varchar(255) DEFAULT '#',
  `is_read` tinyint(1) DEFAULT 0,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `tenant_id` (`tenant_id`),
  KEY `user_id` (`user_id`),
  CONSTRAINT `notifications_ibfk_1` FOREIGN KEY (`tenant_id`) REFERENCES `tenants` (`id`) ON DELETE CASCADE,
  CONSTRAINT `notifications_ibfk_2` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Table: subscriptions
DROP TABLE IF EXISTS `subscriptions`;
CREATE TABLE `subscriptions` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `tenant_id` int(11) NOT NULL,
  `status` enum('trial','active','past_due','cancelled') NOT NULL DEFAULT 'trial',
  `plan` varchar(50) NOT NULL DEFAULT 'standard',
  `card_brand` varchar(50) DEFAULT NULL,
  `card_last4` varchar(4) DEFAULT NULL,
  `card_token` varchar(255) DEFAULT NULL,
  `trial_ends_at` timestamp NULL DEFAULT NULL,
  `next_billing_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `tenant_id` (`tenant_id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

INSERT INTO `subscriptions` VALUES ('1', '1', 'active', 'premium', NULL, NULL, NULL, '2026-01-21 18:07:40', '2026-01-22 23:28:32', '2025-12-22 18:07:40', '2025-12-22 23:28:32');

-- Table: support_messages
DROP TABLE IF EXISTS `support_messages`;
CREATE TABLE `support_messages` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `ticket_id` int(11) NOT NULL,
  `user_id` int(11) NOT NULL,
  `message` text NOT NULL,
  `is_staff` tinyint(1) DEFAULT 0,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `ticket_id` (`ticket_id`),
  CONSTRAINT `support_messages_ibfk_1` FOREIGN KEY (`ticket_id`) REFERENCES `support_tickets` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Table: support_tickets
DROP TABLE IF EXISTS `support_tickets`;
CREATE TABLE `support_tickets` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `tenant_id` int(11) NOT NULL,
  `user_id` int(11) NOT NULL,
  `subject` varchar(255) NOT NULL,
  `status` enum('open','answered','closed') DEFAULT 'open',
  `priority` enum('low','medium','high') DEFAULT 'medium',
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `tenant_id` (`tenant_id`),
  KEY `user_id` (`user_id`),
  CONSTRAINT `support_tickets_ibfk_1` FOREIGN KEY (`tenant_id`) REFERENCES `tenants` (`id`) ON DELETE CASCADE,
  CONSTRAINT `support_tickets_ibfk_2` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Table: system_settings
DROP TABLE IF EXISTS `system_settings`;
CREATE TABLE `system_settings` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `setting_key` varchar(100) NOT NULL,
  `setting_value` text DEFAULT NULL,
  `description` varchar(255) DEFAULT NULL,
  `updated_at` datetime DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `setting_key` (`setting_key`)
) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

INSERT INTO `system_settings` VALUES ('1', 'payment_routing_mode', 'global', 'Determines if payments use global admin keys or tenant specific keys', '2025-12-23 09:22:15'),
('3', 'flutterwave_secret_key', '', 'Global Flutterwave Secret Key', '2025-12-23 09:22:15'),
('4', 'paystack_public_key', '', 'Global Paystack Public Key', '2025-12-23 09:22:15'),
('5', 'paystack_secret_key', '', 'Global Paystack Secret Key', '2025-12-23 09:22:15'),
('6', 'sudo_api_key', '', 'Global Sudo Card API Key', '2025-12-23 09:22:15'),
('7', 'sudo_api_secret', '', 'Global Sudo Card Secret', '2025-12-23 09:22:15'),
('8', 'flutterwave_public_key', 'TEST_PK_694a5167a9d95', NULL, '2025-12-23 09:23:03');

-- Table: tenant_modules
DROP TABLE IF EXISTS `tenant_modules`;
CREATE TABLE `tenant_modules` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `tenant_id` int(11) NOT NULL,
  `module_id` int(11) NOT NULL,
  `status` enum('enabled','disabled') NOT NULL DEFAULT 'disabled',
  PRIMARY KEY (`id`),
  UNIQUE KEY `tenant_module` (`tenant_id`,`module_id`),
  KEY `fk_tm_module` (`module_id`),
  CONSTRAINT `fk_tm_module` FOREIGN KEY (`module_id`) REFERENCES `modules` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_tm_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenants` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

INSERT INTO `tenant_modules` VALUES ('1', '1', '1', 'enabled'),
('2', '1', '2', 'enabled'),
('3', '1', '3', 'enabled'),
('4', '1', '4', 'enabled'),
('5', '1', '5', 'enabled');

-- Table: tenants
DROP TABLE IF EXISTS `tenants`;
CREATE TABLE `tenants` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `domain` varchar(255) DEFAULT NULL COMMENT 'Custom domain',
  `subdomain` varchar(255) NOT NULL COMMENT 'Subdomain prefix',
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `subdomain` (`subdomain`),
  UNIQUE KEY `domain` (`domain`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

INSERT INTO `tenants` VALUES ('1', 'Local Dev', 'localhost', 'localhost', '2025-12-22 18:04:28');

-- Table: transactions
DROP TABLE IF EXISTS `transactions`;
CREATE TABLE `transactions` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `tenant_id` int(11) NOT NULL,
  `user_id` int(11) DEFAULT NULL,
  `reference` varchar(100) NOT NULL,
  `amount` decimal(10,2) NOT NULL,
  `currency` varchar(3) NOT NULL DEFAULT 'USD',
  `status` enum('pending','successful','failed','reversed') NOT NULL DEFAULT 'pending',
  `provider` varchar(50) NOT NULL,
  `meta` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`meta`)),
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `type` enum('deposit','withdrawal','transfer','card_funding','payment') NOT NULL DEFAULT 'payment',
  `recipient_account` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `tenant_id` (`tenant_id`),
  KEY `reference` (`reference`),
  CONSTRAINT `fk_trans_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenants` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Table: users
DROP TABLE IF EXISTS `users`;
CREATE TABLE `users` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `tenant_id` int(11) NOT NULL,
  `email` varchar(255) NOT NULL,
  `name` varchar(255) DEFAULT NULL,
  `phone` varchar(50) DEFAULT NULL,
  `business_name` varchar(255) DEFAULT NULL,
  `password` varchar(255) NOT NULL,
  `role` enum('admin','user') NOT NULL DEFAULT 'user',
  `is_verified` tinyint(1) NOT NULL DEFAULT 0,
  `verification_token` varchar(100) DEFAULT NULL,
  `two_factor_enabled` tinyint(1) NOT NULL DEFAULT 0,
  `two_factor_secret` varchar(255) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `tenant_id` (`tenant_id`),
  CONSTRAINT `fk_users_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenants` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

INSERT INTO `users` VALUES ('1', '1', 'admin@localhost', NULL, NULL, NULL, '$2y$10$8wQ9OIhuczlv7CxSTUaxX.uA3zGotrNV2G6a8w0REhYO8ZeuePsp6', 'admin', '1', NULL, '0', 'TESTSECRET', '2025-12-22 18:04:28'),
('2', '1', 'user@localhost', NULL, NULL, NULL, '$2y$10$ZbuiuMEah0uS65wiMFvCk.m.Q6dqqWePmOEo53RSdI6veZgi5/Xva', 'user', '1', NULL, '0', NULL, '2025-12-22 18:48:04'),
('4', '1', 'democlient@example.com', 'democlient', NULL, NULL, '$2y$10$ZSZYVUAF7O/kl9uos60ItOZz/.bORu6FnoCxhdd.rMXMvL7k1qhZS', '', '1', NULL, '0', NULL, '2025-12-24 19:21:58');

SET FOREIGN_KEY_CHECKS=1;
