<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" type="image/png" href="/favicon.png">
    <title>Admin Dashboard | Casjoe SaaS</title>
    <link rel="stylesheet" href="/css/style.css">
    <script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
    <style>
        .admin-dashboard { display: grid; grid-template-columns: repeat(auto-fit, minmax(250px, 1fr)); gap: 20px; padding: 20px 0; }
        .admin-card { background: white; padding: 25px; border-radius: 12px; box-shadow: 0 4px 15px rgba(0,0,0,0.05); text-align: center; transition: transform 0.2s; text-decoration: none; color: inherit; display: block; }
        .admin-card:hover { transform: translateY(-5px); box-shadow: 0 8px 25px rgba(0,0,0,0.1); }
        .admin-icon { font-size: 3rem; color: var(--primary, #4a90e2); margin-bottom: 15px; }
        .admin-card h3 { margin: 0 0 10px 0; color: #333; }
        .admin-card p { color: #666; font-size: 0.9rem; margin: 0; }
        .stat-value { font-size: 2rem; font-weight: bold; color: #333; margin: 10px 0; display: block;}
    </style>
</head>
<body>
<div class="app-container">
    <?php 
    $sidebarPath = __DIR__ . '/../../../Modules/CasjoeERP/views/layout/sidebar.php';
    if (file_exists($sidebarPath)) {
        require $sidebarPath; 
    }
    ?>
    <main class="main-content">
        <div class="top-bar">
            <h2>Super Admin Dashboard</h2>
            <div class="user-profile">
                <span>Welcome, Admin</span>
            </div>
        </div>

        <div class="admin-dashboard">
            <!-- User Management -->
            <a href="/admin/users" class="admin-card">
                <ion-icon name="people-circle-outline" class="admin-icon" style="color: #6c5ce7;"></ion-icon>
                <h3>Total Users</h3>
                <span class="stat-value"><?= number_format($stats['users']) ?></span>
                <p>Registered Accounts</p>
            </a>

            <!-- Revenue -->
            <div class="admin-card">
                <ion-icon name="cash-outline" class="admin-icon" style="color: #00b894;"></ion-icon>
                <h3>Total Revenue</h3>
                <span class="stat-value">₦<?= number_format($stats['revenue'], 2) ?></span>
                <p>Successful Transactions</p>
            </div>

            <!-- Virtual Cards -->
            <div class="admin-card">
                <ion-icon name="card-outline" class="admin-icon" style="color: #0984e3;"></ion-icon>
                <h3>Virtual Cards</h3>
                <span class="stat-value"><?= number_format($stats['cards']) ?></span>
                <p>Active Cards Created</p>
            </div>

            <!-- Payment Links -->
            <div class="admin-card">
                <ion-icon name="link-outline" class="admin-icon" style="color: #e84393;"></ion-icon>
                <h3>Payment Links</h3>
                <span class="stat-value"><?= number_format($stats['links']) ?></span>
                <p>Generated by Users</p>
            </div>

            <!-- Active Apps -->
            <div class="admin-card">
                <ion-icon name="grid-outline" class="admin-icon" style="color: #fdcb6e;"></ion-icon>
                <h3>Active Apps</h3>
                <span class="stat-value"><?= number_format($stats['apps']) ?></span>
                <p>Modules Installed</p>
            </div>

            <!-- System Settings -->
            <a href="/admin/settings" class="admin-card">
                <ion-icon name="settings-outline" class="admin-icon" style="color: #636e72;"></ion-icon>
                <h3>Settings</h3>
                <p style="margin-top: 15px;">Configure Platform</p>
            </a>

            <!-- Broadcasts -->
            <a href="/admin/broadcast" class="admin-card">
                <ion-icon name="megaphone-outline" class="admin-icon" style="color: #e17055;"></ion-icon>
                <h3>Broadcasts</h3>
                <p style="margin-top: 15px;">Announcements</p>
            </a>

            <!-- System Health -->
            <div class="admin-card" style="opacity: 0.7;">
                <ion-icon name="pulse-outline" class="admin-icon" style="color: #b2bec3;"></ion-icon>
                <h3>System Health</h3>
                <span class="stat-value" style="font-size: 1.5rem; color: green;">Operational</span>
            </div>
        </div>

    </main>
</div>
</body>
</html>
