-- Add the 5 missing PROMOTIONAL templates to complete the set
INSERT INTO `cm_templates` (tenant_id, name, subject, content)
VALUES (
        NULL,
        'Flash Sale - Premium',
        '⚡ Flash Sale: Up to 50% Off - 24 Hours Only!',
        '<!DOCTYPE html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head><body style="margin:0;padding:0;font-family:-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica,Arial,sans-serif;"><table width="100%" cellpadding="0" cellspacing="0" style="background:#f4f4f4;padding:40px 0;"><tr><td align="center"><table width="600" cellpadding="0" cellspacing="0" style="background:#fff;border-radius:8px;overflow:hidden;box-shadow:0 4px 20px rgba(0,0,0,0.1);"><tr><td><img src="https://images.pexels.com/photos/1055691/pexels-photo-1055691.jpeg?auto=compress&cs=tinysrgb&w=600" width="600" height="300" style="display:block;width:100%;height:auto;"></td></tr><tr><td style="padding:40px;text-align:center;"><h1 style="color:#e74c3c;font-size:42px;margin:0 0 10px;">FLASH SALE</h1><p style="font-size:18px;color:#555;margin:0 0 30px;">24 Hours Only - Don''t Miss Out!</p><p style="font-size:16px;line-height:1.6;color:#333;margin:0 0 30px;">Hi {{name}},<br><br>Get ready for massive savings! Enjoy up to 50% off on select items for the next 24 hours.</p><a href="{{link}}" style="display:inline-block;background:#e74c3c;color:#fff;padding:16px 40px;text-decoration:none;border-radius:50px;font-weight:bold;font-size:16px;box-shadow:0 4px 15px rgba(231,76,60,0.3);">Shop Now</a></td></tr><tr><td style="background:#2c3e50;padding:30px;text-align:center;"><div style="margin-bottom:20px;"><a href="https://facebook.com" style="display:inline-block;margin:0 8px;"><img src="https://img.icons8.com/fluency/48/facebook-new.png" width="32" height="32"></a><a href="https://twitter.com" style="display:inline-block;margin:0 8px;"><img src="https://img.icons8.com/fluency/48/twitter.png" width="32" height="32"></a><a href="https://instagram.com" style="display:inline-block;margin:0 8px;"><img src="https://img.icons8.com/fluency/48/instagram-new.png" width="32" height="32"></a><a href="https://linkedin.com" style="display:inline-block;margin:0 8px;"><img src="https://img.icons8.com/fluency/48/linkedin.png" width="32" height="32"></a></div><p style="color:#95a5a6;font-size:14px;margin:0;">&copy; {{year}} {{company_name}}. All rights reserved.</p><p style="margin:10px 0 0;"><a href="{{unsubscribe_url}}" style="color:#95a5a6;font-size:12px;">Unsubscribe</a></p></td></tr></table></td></tr></table></body></html>'
    ),
    (
        NULL,
        'Product Launch - Premium',
        '🚀 Introducing {{product_name}}',
        '<!DOCTYPE html><html><head><meta charset="UTF-8"></head><body style="margin:0;padding:0;"><table width="100%" cellpadding="0" cellspacing="0" style="background:linear-gradient(135deg,#667eea 0%,#764ba2 100%);padding:40px 0;"><tr><td align="center"><table width="600" cellpadding="0" cellspacing="0" style="background:#fff;border-radius:12px;overflow:hidden;"><tr><td><img src="https://images.pexels.com/photos/3861969/pexels-photo-3861969.jpeg?auto=compress&cs=tinysrgb&w=600" width="600" height="350" style="display:block;width:100%;"></td></tr><tr><td style="padding:50px 40px;text-align:center;"><h1 style="color:#1a202c;font-size:36px;margin:0 0 15px;">Meet {{product_name}}</h1><p style="font-size:18px;color:#4a5568;margin:0 0 30px;">Reimagining whats possible</p><a href="{{link}}" style="display:inline-block;background:#667eea;color:#fff;padding:16px 45px;text-decoration:none;border-radius:50px;font-weight:bold;">Learn More</a></td></tr><tr><td style="background:#1a202c;padding:30px;text-align:center;"><div style="margin-bottom:15px;"><a href="#"><img src="https://img.icons8.com/ios-filled/32/ffffff/facebook-new.png" width="28"></a><a href="#" style="margin-left:8px;"><img src="https://img.icons8.com/ios-filled/32/ffffff/twitter.png" width="28"></a><a href="#" style="margin-left:8px;"><img src="https://img.icons8.com/ios-filled/32/ffffff/instagram-new.png" width="28"></a></div><p style="color:#a0aec0;font-size:13px;margin:0;">&copy; {{year}} {{company_name}}</p></td></tr></table></td></tr></table></body></html>'
    ),
    (
        NULL,
        'Winter Sale - Premium',
        '❄️ Winter Sale - 30% Off',
        '<!DOCTYPE html><html><head><meta charset="UTF-8"></head><body style="margin:0;padding:0;"><table width="100%" cellpadding="0" cellspacing="0" style="background:#e8f4f8;padding:40px 0;"><tr><td align="center"><table width="600" cellpadding="0" cellspacing="0" style="background:#fff;border-radius:10px;overflow:hidden;"><tr><td><img src="https://images.pexels.com/photos/265792/pexels-photo-265792.jpeg?auto=compress&cs=tinysrgb&w=600" width="600" height="300" style="display:block;width:100%;"></td></tr><tr><td style="padding:40px;text-align:center;"><h1 style="color:#0077b6;font-size:40px;margin:0 0 10px;">Winter Wonderland ❄️</h1><p style="font-size:22px;color:#023e8a;margin:0 0 25px;">30% OFF EVERYTHING</p><p style="font-size:16px;color:#333;margin:0 0 25px;">Use code <strong style="background:#ffe066;padding:3px 8px;">WINTER30</strong></p><a href="{{link}}" style="display:inline-block;background:#0077b6;color:#fff;padding:15px 40px;text-decoration:none;border-radius:30px;font-weight:bold;">Start Shopping</a></td></tr><tr><td style="padding:30px;background:#023e8a;text-align:center;"><div style="margin-bottom:15px;"><a href="#"><img src="https://img.icons8.com/color/40/facebook-new.png"></a><a href="#" style="margin-left:8px;"><img src="https://img.icons8.com/color/40/twitter--v1.png"></a><a href="#" style="margin-left:8px;"><img src="https://img.icons8.com/color/40/instagram-new--v1.png"></a></div><p style="color:#90e0ef;font-size:13px;margin:0;">&copy; {{year}} {{company_name}}</p></td></tr></table></td></tr></table></body></html>'
    ),
    (
        NULL,
        'VIP Exclusive - Premium',
        '💎 VIP Early Access',
        '<!DOCTYPE html><html><head><meta charset="UTF-8"></head><body style="margin:0;padding:0;"><table width="100%" cellpadding="0" cellspacing="0" style="background:#000;padding:40px 0;"><tr><td align="center"><table width="600" cellpadding="0" cellspacing="0" style="background:#fff;"><tr><td><img src="https://images.pexels.com/photos/1342609/pexels-photo-1342609.jpeg?auto=compress&cs=tinysrgb&w=600" width="600" height="280" style="display:block;width:100%;"></td></tr><tr><td style="padding:50px;text-align:center;"><h1 style="color:#1a1a1a;font-size:38px;margin:0 0 20px;">Early Access</h1><p style="font-size:16px;color:#333;margin:0 0 30px;">Dear {{name}}, you get first access to our new collection.</p><a href="{{link}}" style="display:inline-block;background:#d4af37;color:#000;padding:16px 40px;text-decoration:none;font-weight:bold;">ENTER VIP SHOP</a></td></tr><tr><td style="padding:25px;background:#1a1a1a;text-align:center;"><div style="margin-bottom:12px;"><a href="#"><img src="https://img.icons8.com/ios-glyphs/30/d4af37/facebook-new.png"></a><a href="#" style="margin-left:8px;"><img src="https://img.icons8.com/ios-glyphs/30/d4af37/instagram-new.png"></a></div><p style="color:#888;font-size:12px;margin:0;">&copy; {{year}} {{company_name}}</p></td></tr></table></td></tr></table></body></html>'
    ),
    (
        NULL,
        'Review Request - Premium',
        '⭐ Rate Your Experience',
        '<!DOCTYPE html><html><head><meta charset="UTF-8"></head><body style="margin:0;padding:0;"><table width="100%" cellpadding="0" cellspacing="0" style="background:#f8f9fa;padding:40px 0;"><tr><td align="center"><table width="600" cellpadding="0" cellspacing="0" style="background:#fff;border-radius:8px;"><tr><td style="padding:40px;text-align:center;"><h2 style="color:#333;font-size:28px;margin:0 0 15px;">We''d Love Your Feedback!</h2><p style="font-size:16px;color:#666;margin:0 0 30px;">Hi {{name}}, how would you rate your experience?</p><div style="margin:25px 0;"><a href="{{link}}&rating=5" style="font-size:40px;text-decoration:none;margin:0 5px;">⭐</a><a href="{{link}}&rating=4" style="font-size:40px;text-decoration:none;margin:0 5px;">⭐</a><a href="{{link}}&rating=3" style="font-size:40px;text-decoration:none;margin:0 5px;">⭐</a></div></td></tr><tr><td style="padding:20px;background:#f1f3f5;text-align:center;"><div style="margin-bottom:10px;"><a href="#"><img src="https://img.icons8.com/color/32/facebook.png"></a><a href="#" style="margin-left:10px;"><img src="https://img.icons8.com/color/32/twitter.png"></a></div><p style="color:#6c757d;font-size:12px;margin:0;">&copy; {{year}} {{company_name}}</p></td></tr></table></td></tr></table></body></html>'
    );